"use client";
import { Camera, Sparkles, Trash2, Utensils } from "lucide-react";
import type { Meal } from "@/types";

export function MealCard({ meal, onDelete }: { meal: Meal; onDelete?: () => void }) { return <div className="life-card group rounded-2xl p-4"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-gold-400/10 text-gold-500"><Utensils className="size-5" /></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{meal.name}</p><p className="text-[11px] text-zinc-500">{meal.mealTime} · {meal.notes}</p></div><div className="text-right"><p className="text-sm font-bold">{meal.calories} kcal</p><p className="text-[10px] text-zinc-400">P {meal.proteins}g · C {meal.carbs}g · G {meal.fats}g</p></div>{onDelete&&<button onClick={onDelete} className="hidden rounded-lg p-2 text-zinc-400 hover:bg-red-500/10 hover:text-red-500 group-hover:block"><Trash2 className="size-4" /></button>}</div></div> }
export function NutritionSummary({ calories, proteins, carbs, fats }: { calories:number; proteins:number; carbs:number; fats:number }) { return <div className="life-card rounded-2xl p-5"><p className="text-sm font-semibold">Resumo do dia</p><div className="mt-5 grid grid-cols-2 gap-4"><Macro label="Calorias" value={`${calories}`} target="2.200 kcal" pct={calories/22}/><Macro label="Proteínas" value={`${proteins}g`} target="140g" pct={proteins/1.4}/><Macro label="Carboidratos" value={`${carbs}g`} target="260g" pct={carbs/2.6}/><Macro label="Gorduras" value={`${fats}g`} target="70g" pct={fats/.7}/></div></div> }
function Macro({label,value,target,pct}:{label:string;value:string;target:string;pct:number}) { return <div><div className="flex items-end justify-between"><div><p className="text-[10px] text-zinc-500">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div><span className="text-[9px] text-zinc-400">/ {target}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-zinc-100 dark:bg-white/[.06]"><i className="block h-full rounded-full bg-gold-400" style={{width:`${Math.min(100,pct)}%`}} /></div></div> }
export function MealUploadBox() { return <label className="flex min-h-40 cursor-not-allowed flex-col items-center justify-center rounded-2xl border border-dashed border-zinc-300 bg-zinc-50/60 p-5 text-center opacity-70 dark:border-zinc-700 dark:bg-white/[.02]"><input type="file" accept="image/*" className="sr-only" disabled/><span className="grid size-11 place-items-center rounded-xl bg-zinc-400 text-white dark:bg-zinc-700"><Camera className="size-5" /></span><p className="mt-3 text-xs font-semibold">Imagem da refeição</p><p className="mt-1 max-w-xs text-[10px] leading-4 text-zinc-500">Em breve: análise automática da refeição por imagem com IA.</p></label> }
export function NutritionInsightCard({ text }: { text:string }) { return <div className="rounded-2xl border border-gold-400/20 bg-gradient-to-br from-gold-400/10 to-transparent p-5"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-gold-500"><Sparkles className="size-4"/>Insight nutricional</div><p className="mt-4 text-sm font-medium leading-6">{text}</p></div> }
export function MacroChart({ proteins, carbs, fats }: { proteins:number; carbs:number; fats:number }) { const total=Math.max(1,proteins+carbs+fats); return <div className="life-card rounded-2xl p-5"><p className="text-sm font-semibold">Distribuição de macros</p><div className="mt-6 flex items-center gap-6"><div className="grid size-32 place-items-center rounded-full" style={{background:`conic-gradient(#d4af37 0 ${proteins/total*100}%,#71717a 0 ${(proteins+carbs)/total*100}%,#60a5fa 0)`}}><div className="grid size-20 place-items-center rounded-full bg-white text-center dark:bg-[#121212]"><span className="text-xs font-bold">{total}g<small className="block text-[9px] font-normal text-zinc-400">total</small></span></div></div><div className="space-y-3 text-xs"><Key color="bg-gold-400" label="Proteínas" value={proteins}/><Key color="bg-zinc-500" label="Carboidratos" value={carbs}/><Key color="bg-blue-400" label="Gorduras" value={fats}/></div></div></div> }
function Key({color,label,value}:{color:string;label:string;value:number}) { return <div className="flex items-center gap-2"><i className={`size-2 rounded-full ${color}`}/><span className="text-zinc-500">{label}</span><strong>{value}g</strong></div> }
