"use client";
import { useState } from "react";
import { Plus } from "lucide-react";
import { useLifeData } from "@/hooks/useLifeData";
import { MealCard, MealUploadBox } from "@/components/nutrition/nutrition-widgets";
import { PageHeader } from "@/components/life/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "@/hooks/useToast";
export default function MealsPage(){const d=useLifeData();const[show,setShow]=useState(false);const[name,setName]=useState("");const[cal,setCal]=useState("450");const[proteins,setProteins]=useState("0");const[carbs,setCarbs]=useState("0");const[fats,setFats]=useState("0");const[notes,setNotes]=useState("");function add(){if(!name.trim())return;d.addMeal({name:name.trim(),calories:Number(cal)||0,proteins:Number(proteins)||0,carbs:Number(carbs)||0,fats:Number(fats)||0,mealTime:new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}),notes:notes.trim()||"Registro manual"});setName("");setCal("450");setProteins("0");setCarbs("0");setFats("0");setNotes("");setShow(false);toast({title:"Refeição registrada",description:"Seu resumo nutricional foi atualizado.",variant:"success"})}return <div className="space-y-7"><PageHeader eyebrow="Alimentação · Refeições" title="Seu diário alimentar." description="Registre o que comeu com rapidez. Os dados ficam prontos para uma futura análise inteligente." action={<Button onClick={()=>setShow(v=>!v)} className="rounded-xl bg-gold-400 text-black"><Plus className="mr-2 size-4"/>Nova refeição</Button>}/>{show&&<div className="life-card grid gap-4 rounded-2xl p-5 lg:grid-cols-[1fr_.7fr]"><div className="space-y-3"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome da refeição" aria-label="Nome da refeição" className="h-11 rounded-xl" autoFocus/><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="space-y-1"><Label htmlFor="meal-cal" className="text-[10px] text-zinc-500">Calorias</Label><Input id="meal-cal" value={cal} onChange={e=>setCal(e.target.value)} type="number" min="0" /></div><div className="space-y-1"><Label htmlFor="meal-p" className="text-[10px] text-zinc-500">Proteínas (g)</Label><Input id="meal-p" value={proteins} onChange={e=>setProteins(e.target.value)} type="number" min="0" /></div><div className="space-y-1"><Label htmlFor="meal-c" className="text-[10px] text-zinc-500">Carboidratos (g)</Label><Input id="meal-c" value={carbs} onChange={e=>setCarbs(e.target.value)} type="number" min="0" /></div><div className="space-y-1"><Label htmlFor="meal-f" className="text-[10px] text-zinc-500">Gorduras (g)</Label><Input id="meal-f" value={fats} onChange={e=>setFats(e.target.value)} type="number" min="0" /></div></div><Textarea value={notes} onChange={e=>setNotes(e.target.value)} className="min-h-24" placeholder="Observações" /><Button onClick={add} className="w-full rounded-xl bg-zinc-950 text-white dark:bg-gold-400 dark:text-black">Salvar refeição</Button></div><MealUploadBox/></div>}<div className="grid gap-3">{d.meals.map(m=><MealCard key={m.id} meal={m} onDelete={()=>{d.deleteMeal(m.id);toast({title:"Refeição removida"})}}/>)}</div></div>}
