"use client";

import { useEffect, useState } from "react";
import { CalendarDays, Check, Edit3, Goal as GoalIcon, LoaderCircle, Plus, Trash2, X } from "lucide-react";
import { useGoals, type GoalInput } from "@/hooks/useGoals";
import type { Goal } from "@/types";
import { formatCurrency, formatDate } from "@/utils/formatting";
import { PageHeader } from "@/components/life/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { EmptyState } from "@/components/ui/empty-state";
import { useToast } from "@/hooks/useToast";

const blank = { name: "", target: "", current: "0", deadline: "", category: "", priority: "medium" as Goal["priority"], description: "" };
const selectClass = "h-11 w-full rounded-xl border border-zinc-200 bg-white px-3.5 text-sm shadow-sm hover:border-zinc-300 focus:border-gold-400 focus:outline-none focus:ring-4 focus:ring-gold-400/10 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-50";

export default function GoalsPage() {
  const { goals, fetchGoals, createGoal, updateGoal, deleteGoal, loading, error } = useGoals();
  const { toast } = useToast();
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<string | null>(null);
  const [form, setForm] = useState(blank);
  const [saving, setSaving] = useState(false);
  useEffect(() => { void fetchGoals(); }, [fetchGoals]);
  function close() { setOpen(false); setEditing(null); setForm(blank); }
  function edit(goal: Goal) { setEditing(goal.id); setForm({ name: goal.name, target: String(goal.target_value), current: String(goal.current_value), deadline: goal.deadline, category: goal.category ?? "", priority: goal.priority, description: goal.description ?? "" }); setOpen(true); }
  async function submit(event: React.FormEvent) { event.preventDefault(); const target = Number(form.target); const current = Number(form.current); if (!form.name.trim() || target <= 0 || current < 0 || !form.deadline) return toast({ variant: "destructive", title: "Revise a meta", description: "Informe nome, valores válidos e prazo." }); const input: GoalInput = { name: form.name.trim(), target_value: target, current_value: current, deadline: form.deadline, category: form.category.trim(), priority: form.priority, description: form.description.trim() || null, status: current >= target ? "completed" : "active" }; setSaving(true); try { if (editing) await updateGoal(editing, input); else await createGoal(input); toast({ variant: "success", title: editing ? "Meta atualizada" : "Meta criada" }); close(); } catch (cause) { toast({ variant: "destructive", title: "Não foi possível salvar", description: cause instanceof Error ? cause.message : "Tente novamente." }); } finally { setSaving(false); } }
  async function remove(id: string) { if (!window.confirm("Excluir esta meta?")) return; try { await deleteGoal(id); toast({ title: "Meta excluída" }); } catch (cause) { toast({ variant: "destructive", title: "Não foi possível excluir", description: cause instanceof Error ? cause.message : "Tente novamente." }); } }
  async function complete(goal: Goal) { try { await updateGoal(goal.id, { status: "completed", current_value: Number(goal.target_value) }); toast({ variant: "success", title: "Meta concluída. Parabéns!" }); } catch (cause) { toast({ variant: "destructive", title: "Não foi possível concluir", description: cause instanceof Error ? cause.message : "Tente novamente." }); } }

  return <div className="space-y-7"><PageHeader eyebrow="Progresso" title="Metas" description="Planos concretos, acompanhados de perto." action={<Button onClick={() => { close(); setOpen(true); }} className="rounded-xl bg-zinc-950 text-white dark:bg-gold-400 dark:text-black"><Plus className="mr-2 size-4" />Nova meta</Button>} />
    {error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-200">{error}</div>}
    {open && <div className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-soft sm:p-7 dark:border-zinc-800 dark:bg-zinc-950"><div className="mb-6 flex justify-between"><div><h2 className="font-display text-xl font-semibold">{editing ? "Editar meta" : "Nova meta"}</h2><p className="mt-1 text-xs text-zinc-500">Dê nome, valor e prazo ao seu próximo passo.</p></div><button onClick={close} className="rounded-xl p-2 hover:bg-zinc-100 dark:hover:bg-zinc-900" aria-label="Fechar"><X className="size-5" /></button></div><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><div className="space-y-2"><Label htmlFor="goal-name">Nome</Label><Input id="goal-name" placeholder="Ex.: Reserva de emergência" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="space-y-2"><Label htmlFor="target">Valor alvo</Label><Input id="target" type="number" min="1" step="0.01" value={form.target} onChange={e=>setForm({...form,target:e.target.value})}/></div><div className="space-y-2"><Label htmlFor="current">Valor atual</Label><Input id="current" type="number" min="0" step="0.01" value={form.current} onChange={e=>setForm({...form,current:e.target.value})}/></div><div className="space-y-2"><Label htmlFor="deadline">Prazo</Label><Input id="deadline" type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></div><div className="space-y-2"><Label htmlFor="goal-category">Categoria</Label><Input id="goal-category" placeholder="Viagem, casa, reserva…" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></div><div className="space-y-2"><Label htmlFor="priority">Prioridade</Label><select id="priority" className={selectClass} value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Goal["priority"]})}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option></select></div><div className="space-y-2 md:col-span-2 xl:col-span-3"><Label htmlFor="description">Descrição</Label><Textarea id="description" placeholder="Por que esta meta importa?" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={close}>Cancelar</Button><Button disabled={saving}>{saving && <LoaderCircle className="mr-2 size-4 animate-spin" />}{editing ? "Salvar alterações" : "Criar meta"}</Button></div></form></div>}
    {loading && !goals.length ? <div className="p-10 text-center text-sm text-zinc-500">Carregando…</div> : goals.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{goals.map(goal => { const progress = Math.min(100, (Number(goal.current_value) / Number(goal.target_value)) * 100); return <article key={goal.id} className="life-card rounded-2xl p-5"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-gold-400/15 text-gold-500"><GoalIcon className="size-5" /></span><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${goal.status === "completed" ? "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300" : "bg-zinc-100 text-zinc-500 dark:bg-zinc-900"}`}>{goal.status === "completed" ? "CONCLUÍDA" : goal.priority === "high" ? "ALTA PRIORIDADE" : "EM ANDAMENTO"}</span></div><h2 className="mt-5 truncate font-display text-lg font-semibold">{goal.name}</h2><p className="mt-1 text-xs text-zinc-500">{goal.category || "Meta financeira"}</p><div className="mt-6 flex justify-between text-xs"><span>{formatCurrency(Number(goal.current_value))}</span><span className="font-semibold">{progress.toFixed(0)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-zinc-100 dark:bg-zinc-800"><div className="h-full rounded-full bg-gold-400" style={{width:`${progress}%`}} /></div><div className="mt-4 flex items-center gap-2 text-xs text-zinc-500"><CalendarDays className="size-4" />Até {formatDate(goal.deadline)} · alvo {formatCurrency(Number(goal.target_value))}</div><div className="mt-5 flex gap-2">{goal.status !== "completed" && <Button size="sm" className="flex-1" onClick={() => complete(goal)}><Check className="mr-1 size-4" />Concluir</Button>}<Button size="sm" variant="outline" onClick={() => edit(goal)} aria-label={`Editar ${goal.name}`}><Edit3 className="size-4" /></Button><Button size="sm" variant="outline" onClick={() => remove(goal.id)} aria-label={`Excluir ${goal.name}`}><Trash2 className="size-4 text-red-500" /></Button></div></article>; })}</div> : <div className="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><EmptyState icon={GoalIcon} title="Nenhuma meta criada" description="Transforme um plano em um valor, um prazo e pequenos avanços." action={<Button onClick={()=>setOpen(true)} size="sm"><Plus className="mr-2 size-4" />Criar primeira meta</Button>} /></div>}
  </div>;
}
