"use client";
import { useState } from "react";
import { Plus } from "lucide-react";
import { useLifeData } from "@/hooks/useLifeData";
import { TaskCard } from "@/components/routine/task-card";
import { PageHeader } from "@/components/life/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "@/hooks/useToast";
const filters = [{ label: "Todas", value: "all" as const }, { label: "Pendentes", value: "pending" as const }, { label: "Concluídas", value: "completed" as const }];

export default function TasksPage(){const data=useLifeData();const[show,setShow]=useState(false);const[title,setTitle]=useState("");const[filter,setFilter]=useState<"all"|"pending"|"completed">("all");function add(){if(!title.trim())return;data.addTask({title:title.trim(),description:"Adicionada ao planejamento pessoal",priority:"medium",dueDate:new Date().toISOString().slice(0,10)});setTitle("");setShow(false);toast({title:"Tarefa criada",variant:"success"})}const visible=data.tasks.filter(t=>filter==="all"||t.status===filter);return <div className="space-y-7"><PageHeader eyebrow="Rotina · Tarefas" title="O essencial, em movimento." description="Transforme planos em próximos passos claros, sem sobrecarregar sua agenda." action={<Button onClick={()=>setShow(v=>!v)} className="rounded-xl bg-gold-400 text-black"><Plus className="mr-2 size-4"/>Nova tarefa</Button>}/>{show&&<div className="life-card flex flex-col gap-3 rounded-2xl p-4 sm:flex-row"><Input value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="O que precisa ser feito?" aria-label="Título da nova tarefa" className="h-11 rounded-xl" autoFocus/><Button onClick={add} className="h-11 rounded-xl bg-zinc-950 text-white dark:bg-gold-400 dark:text-black">Criar tarefa</Button></div>}<div className="flex gap-2" role="tablist" aria-label="Filtrar tarefas">{filters.map(f=><button key={f.value} role="tab" aria-selected={filter===f.value} onClick={()=>setFilter(f.value)} className={`rounded-full px-3 py-1.5 text-[11px] font-semibold transition ${filter===f.value?"bg-zinc-950 text-white dark:bg-gold-400 dark:text-black":"border border-zinc-200 text-zinc-500 hover:border-zinc-300 dark:border-white/10 dark:hover:border-white/20"}`}>{f.label}</button>)}</div>{visible.length?<div className="grid gap-3 lg:grid-cols-2">{visible.map(t=><TaskCard key={t.id} task={t} onToggle={()=>data.toggleTask(t.id)} onDelete={()=>data.deleteTask(t.id)}/>)}</div>:<p className="py-10 text-center text-sm text-zinc-500">Nenhuma tarefa {filter==="pending"?"pendente":"concluída"} por aqui.</p>}</div>}
