"use client";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Flame, Gauge, ListChecks, Plus } from "lucide-react";
import { useLifeData } from "@/hooks/useLifeData";
import { PageHeader, MetricCard } from "@/components/life/page-header";
import { HabitCard } from "@/components/routine/habit-card";
import { TaskCard } from "@/components/routine/task-card";
import { RoutineCalendar, TimeTrackerCard, WeeklyProgress } from "@/components/routine/routine-widgets";
import { Button } from "@/components/ui/button";

export default function RoutinePage() { const data=useLifeData(); return <div className="space-y-7"><PageHeader eyebrow="Rotina" title="Seu tempo, com intenção." description="Organize hábitos, tarefas e blocos de foco em uma rotina que cabe na vida real." action={<Button asChild className="gold-glow rounded-xl bg-gold-400 text-black hover:bg-gold-300"><Link href="/routine/tasks"><Plus className="mr-2 size-4"/>Nova tarefa</Link></Button>}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Hábitos hoje" value={`${data.metrics.completedHabits}/${data.habits.length}`} detail="concluídos até agora" icon={CheckCircle2} accent="green"/><MetricCard label="Tarefas feitas" value={`${data.metrics.completedTasks}/${data.tasks.length}`} detail="no seu planejamento" icon={ListChecks}/><MetricCard label="Sequência máxima" value={`${Math.max(0,...data.habits.map(h=>h.streak))} dias`} detail="continue no seu ritmo" icon={Flame}/><MetricCard label="Consistência" value={`${data.metrics.routine}%`} detail="da rotina esta semana" icon={Gauge} accent="blue"/></div><div className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><div className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-display text-lg font-semibold">Hábitos de hoje</h2><p className="text-[11px] text-zinc-500">Pequenas ações, repetidas com consistência.</p></div><Link href="/routine/habits" className="flex items-center gap-1 text-xs font-semibold text-gold-500">Ver todos <ArrowRight className="size-3"/></Link></div><div className="grid gap-3 md:grid-cols-2">{data.habits.slice(0,4).map(h=><HabitCard key={h.id} habit={h} onToggle={()=>data.toggleHabit(h.id)}/>)}</div></div><TimeTrackerCard/></div><div className="grid gap-4 lg:grid-cols-2"><WeeklyProgress value={data.metrics.routine}/><RoutineCalendar/></div><div><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-lg font-semibold">Próximas tarefas</h2><Link href="/routine/tasks" className="text-xs font-semibold text-gold-500">Abrir planejamento</Link></div><div className="grid gap-3 lg:grid-cols-2">{data.tasks.slice(0,4).map(t=><TaskCard key={t.id} task={t} onToggle={()=>data.toggleTask(t.id)}/>)}</div></div></div> }
