"use client";
import Link from "next/link";
import { useEffect, useMemo } from "react";
import { ArrowRight, Bot, CheckCircle2, CircleDollarSign, Goal, HeartPulse, Plus, Salad, Sparkles, TrendingUp } from "lucide-react";
import { useAuth } from "@/context/auth";
import { useGoals } from "@/hooks/useGoals";
import { useTransactions } from "@/hooks/useTransactions";
import { useLifeData } from "@/hooks/useLifeData";
import { getFinancialSummary } from "@/lib/finance";
import { formatCurrency } from "@/utils/formatting";
import { PageHeader, MetricCard } from "@/components/life/page-header";
import { HabitCard } from "@/components/routine/habit-card";
import { MealCard } from "@/components/nutrition/nutrition-widgets";
import { WeeklyProgress } from "@/components/routine/routine-widgets";
import { Button } from "@/components/ui/button";

export default function DashboardPage() {
  const { profile }=useAuth(); const {transactions,fetchTransactions}=useTransactions(); const {goals,fetchGoals}=useGoals(); const life=useLifeData();
  useEffect(()=>{void fetchTransactions();void fetchGoals()},[fetchTransactions,fetchGoals]);
  const financial=useMemo(()=>getFinancialSummary(transactions,goals),[transactions,goals]);
  const lifeScore=Math.round(financial.score*.4+life.metrics.routine*.35+life.metrics.nutrition*.25);
  const first=profile?.full_name?.split(" ")[0]||"por aqui";
  return <div className="space-y-7"><PageHeader eyebrow="Life Dashboard" title={`Olá, ${first}.`} description="Dinheiro, tempo e alimentação em uma visão simples do que está funcionando — e do próximo passo que vale a pena." action={<Button asChild className="gold-glow rounded-xl bg-gold-400 text-black"><Link href="/transactions?novo=1"><Plus className="mr-2 size-4"/>Novo registro</Link></Button>}/>
    <section className="relative overflow-hidden rounded-[28px] bg-zinc-950 p-6 text-white sm:p-8 dark:border dark:border-white/10"><div className="absolute -right-20 -top-28 size-72 rounded-full bg-gold-400/15 blur-3xl"/><div className="relative grid gap-8 lg:grid-cols-[.7fr_1.3fr] lg:items-center"><div className="flex items-center gap-5"><div className="relative grid size-28 shrink-0 place-items-center rounded-full bg-[conic-gradient(#d4af37_var(--score),#27272a_0)] p-2" style={{"--score":`${lifeScore}%`} as React.CSSProperties}><div className="grid size-full place-items-center rounded-full bg-zinc-950"><div className="text-center"><strong className="font-display text-3xl">{lifeScore}</strong><span className="block text-[9px] uppercase tracking-wider text-zinc-500">de 100</span></div></div></div><div><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.16em] text-gold-300"><Sparkles className="size-3.5"/>Life Score</p><h2 className="mt-2 font-display text-xl font-semibold">Sua vida em equilíbrio.</h2><p className="mt-1 max-w-sm text-xs leading-5 text-zinc-400">O índice combina organização financeira, rotina, alimentação e metas ativas.</p></div></div><div className="grid grid-cols-3 gap-2">{[{l:"Finanças",v:financial.score},{l:"Rotina",v:life.metrics.routine},{l:"Alimentação",v:life.metrics.nutrition}].map(x=><div key={x.l} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><p className="text-[10px] text-zinc-500">{x.l}</p><p className="mt-2 font-display text-xl font-semibold">{x.v}</p><div className="mt-3 h-1 overflow-hidden rounded-full bg-white/10"><i className="block h-full rounded-full bg-gold-400" style={{width:`${x.v}%`}}/></div></div>)}</div></div></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Saúde financeira" value={formatCurrency(financial.balance)} detail="saldo do mês" icon={CircleDollarSign} accent="green"/><MetricCard label="Produtividade" value={`${life.metrics.routine}%`} detail="progresso semanal" icon={TrendingUp}/><MetricCard label="Alimentação hoje" value={`${life.metrics.calories} kcal`} detail={`${life.meals.length} refeições registradas`} icon={Salad} accent="blue"/><MetricCard label="Hábitos" value={`${life.metrics.completedHabits}/${life.habits.length}`} detail="concluídos hoje" icon={CheckCircle2}/><MetricCard label="Metas ativas" value={`${financial.activeGoals.length}`} detail="objetivos em andamento" icon={Goal}/></div>
    <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><WeeklyProgress value={life.metrics.routine}/><div className="flex flex-col justify-between overflow-hidden rounded-2xl bg-gradient-to-br from-gold-300 to-gold-500 p-6 text-black"><div><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-black text-gold-300"><Bot className="size-5"/></span><span className="text-[9px] font-bold uppercase tracking-[.18em] opacity-60">Insight conectado</span></div><p className="mt-8 font-display text-xl font-semibold leading-7">Sua produtividade foi maior nos dias em que você completou a rotina matinal.</p><p className="mt-2 text-xs leading-5 opacity-65">O FinBot cruza seus registros para revelar padrões entre dinheiro, tempo e saúde.</p></div><Link href="/finbot" className="mt-6 inline-flex items-center gap-2 text-xs font-bold">Conversar com o FinBot <ArrowRight className="size-3.5"/></Link></div></div>
    <div className="grid gap-5 lg:grid-cols-2"><section><div className="mb-3 flex items-center justify-between"><h2 className="font-display text-lg font-semibold">Hábitos de hoje</h2><Link href="/routine/habits" className="text-xs font-semibold text-gold-500">Ver rotina</Link></div><div className="space-y-3">{life.habits.slice(0,2).map(h=><HabitCard key={h.id} habit={h} onToggle={()=>life.toggleHabit(h.id)}/>)}</div></section><section><div className="mb-3 flex items-center justify-between"><h2 className="font-display text-lg font-semibold">Alimentação do dia</h2><Link href="/nutrition/meals" className="text-xs font-semibold text-gold-500">Registrar refeição</Link></div><div className="space-y-3">{life.meals.slice(0,2).map(m=><MealCard key={m.id} meal={m}/>)}</div></section></div>
    <div className="life-card flex flex-col items-start gap-4 rounded-2xl p-5 sm:flex-row sm:items-center"><span className="grid size-11 place-items-center rounded-xl bg-emerald-500/10 text-emerald-500"><HeartPulse className="size-5"/></span><div className="flex-1"><p className="text-sm font-semibold">Você está construindo consistência.</p><p className="mt-1 text-xs text-zinc-500">Seu Life Score sobe com registros simples e frequentes — não com dias perfeitos.</p></div><Link href="/routine" className="text-xs font-bold text-gold-500">Planejar meu dia →</Link></div>
  </div>;
}
